//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendasWeb.SAC {
    
    
    public partial class HomeAtividadesWebForm {
        
        /// <summary>
        /// PainelFiltrosLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal PainelFiltrosLiteral;
        
        /// <summary>
        /// AtividadeWebUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VendasWeb.usercontrol.AtividadeWebUserControl AtividadeWebUserControl;
    }
}
